Algoritmo "idade"

Var

  idade1, idade2, idade3, idade4: real

  nome1, nome2, nome3, nome4: caracter
  
Inicio

  escreval("digite o nome de 4 pessoas:")
   leia(nome1)
   leia(nome2)
   leia(nome3)
   leia(nome4)
  escreval("agora digite a idade destas pessosa:")
   leia(idade1)
   leia(idade2)
   leia(idade3)
   leia(idade4)
  escreva("a media de idade destas pessoas é:", (idade1+idade2+idade3+idade4)/4)
Fimalgoritmo