Algoritmo "Média notas"

Var
   nota1, nota2, nota3: real
   media_final: real

Inicio

      escreval("Digite a nota do primeiro bimestre:")
      leia(nota1)

      escreval("Digite a nota do segundo bimestre:")
      leia(nota2)

      escreval("Digite a nota do terceito bimestre")
      leia(nota3)

      media_final<-(nota1+nota2+nota3)/3
      escreva("Sua média final é:", media_final)
Fimalgoritmo