Algoritmo "salario"

Var

  nome, profissao: caracter
  idade, salario: real

Inicio

      escreva("digite seu nome: ")
       leia(nome)
      escreva("digite sua profissão: ")
       leia(profissao)
      escreva("digite sua idade: ")
       leia(idade)
      escreva("digite seu salario: ")
       leia(salario)

      escreva("seu novo salario com as despesas de saude será:", (salario-(salario/100)*13):10:2)


Fimalgoritmo