Algoritmo "Volume_Prisma"

Var
 Lado1: real
 Lado2: real
 Lado3: real
 Volume: real

Inicio
      escreval("Digite qual o tamanho do primeiro lado de sua pirâmide")
      Leia (Lado1)
      escreval("Digite qual o tamanho do segundo lado de sua pirâmide")
      Leia (Lado2)
      escreval("Digite qual o tamanho do terceiro lado de sua pirâmide")
      Leia (Lado3)
      Volume <- Lado1*Lado2*Lado3
      escreval("O volume de seu prisma é:", Volume)
      

Fimalgoritmo