Algoritmo "6.Genero e idade"

Var

  sexo,nome: caracter
  idade: inteiro

Inicio

      escreva("qual seu nome: ")
       leia(nome)
       
      repita
       escreva("qual sua idade: ")
       leia(idade)
      ate (idade>=10) e (idade<=100)
      
      repita
       escreva("Qual seu genero(F/M): ")
       leia(sexo)
      ate (sexo = "f") ou (sexo = "m")


Fimalgoritmo