Algoritmo "semnome"

Var

   nome: caracter
   idade: inteiro

Inicio

      escreva("Digite seu nome: ")
      leia(nome)
      
      escreva("Digite sua idade: ")
      leia(idade)
      
      se idade>=18 então
       escreva("você está apto a tirar a carteira de motorista")

      fimse

      se idade<18 então
       escreva("você não pode tirar a cnh")
      fimse

Fimalgoritmo