Algoritmo "semnome"

Var

 n1, n2: real


Inicio

  escreva("digite o primeiro numero: ")
   leia(n1)
  escreva("digite o segundo numero: ")
   leia(n2)

  se n1>n2 então
   escreva("seu primeiro número é maior que o segundo")
  fimse

  se n2>n1 então
   escreva("segundo numero é maior que o primeiro")
  fimse
  
  se n1=n2 então
   escreva("os dois valores são identicos")
  fimse

Fimalgoritmo