Algoritmo "8.passou"

Var

nota1,nota2,frequencia: real


Inicio

      escreva("Digite sua primeira nota: ")
       leia(nota1)
      escreva("Digite sua segunda nota: ")
       leia(nota2)
      escreva("digite sua porcentagem de frequencia: ")
       leia(frequencia)
       
       se ((nota1+nota2)/2)>=6.0 e (frequencia>=75) então
        escreva("você foi aprovado")
       senao
        escreva("você não foi aprovado")
       fimse


Fimalgoritmo