algoritmo "21.Amor"
// Função :
// Autor :
// Data : 09/09/2022
// Seção de Declarações
var

pal,pal2: caracter
n1: inteiro

inicio

escreva("digite uma frase: ")
leia(pal)

//O ultimo exercicio foi tão dificil e isso aq é isso

para n1 de 1 ate compr(pal) faca
   pal2:=copia(pal,n1,4)
   se(pal2="amor") entao
      escreva("entendi o esquema")
   fimse
fimpara



fimalgoritmo
