algoritmo "23.ASCIIconsoante"
// Função :
// Autor :
// Data : 11/09/2022
// Seção de Declarações
var
x:inteiro
inicio

para x de 65 ate 90 faca
   se(x=65) ou (x=69) ou (x=73) ou (x=79) ou (x=85) entao
      escreval("vogal")
   senao
      escreval(carac(x),"=",x)
   fimse
fimpara

para x de 97 ate 122 faca
   se(x=97) ou (x=101) ou (x=105) ou (x=111) ou (x=117) entao
      escreval("vogal")
   senao
      escreval(carac(x),"=",x)
   fimse
fimpara

fimalgoritmo
